Prefix: '&7[&6BuildingGadget&7]'

#Permission to check before player use it
Permission:
  Enable: true

#Name of Building Gadget
ToolName: '&6Building Gadget'

#Lore of Building Gadget
ToolLore: 'Use This To Make Your Build Easy'

##Item you want to be Building Gadget Item
Item: 'BLAZE_ROD'

##Custom ModelData of Item to make Building Gadget Texture. if negative number it will not require Custom Model Data to function
CustomModelData: 1050

#All Message
Messages:
  OnlyPlayers: '&cOnly players can use this command.'
  NoPermission: '&cYou do not have permission to use this.'
  ReceivedGadget: '&aYou have received a Building Gadget.'
  FirstBlockSelected: '&aFirst block selected.'
  Cancel-Massage: '&aCancel Selected Success.'
  SecondBlockSelected: '&aSecond block selected.'
  BothBlocksSelected: '&aSelected all successfully use: &f/bgadget confirm &ato place blocks or &f/bgadget cancel &ato Cancel all Selected.'
  MustSelectFirst: '&aYou must select the first block by using LEFT-CLICK first.'
  NotEnoughBlocks: '&cNot enough blocks in your inventory, You Need:'
  BlocksPlaced: '&aBlocks placed successfully.'
  InvalidFirstBlock: '&cThe first selected block is AIR. Please select a valid block.'
  ConfigReloaded: '&aConfiguration has been reloaded.'
  InvalidSelection: '&cYou must select blocks.'