Prefix: '&7[&6BuildingGadget&7]'

#Name of Building Gadget
ToolName: '&6Building Gadget'

#Lore of Building Gadget
ToolLore: 'Use This To Make Your Build Easy'

##Item you want to be Building Gadget Item
Item: 'BLAZE_ROD'

##Custom ModelData of Item to make Building Gadget Texture
CustomModelData: 1050

#All Message
Messages:
  OnlyPlayers: 'Only players can use this command.'
  NoPermission: 'You do not have permission to use this command.'
  ReceivedGadget: 'You have received a Building Gadget.'
  FirstBlockSelected: 'First block selected.'
  SecondBlockSelected: 'Second block selected.'
  BothBlocksSelected: 'Both blocks already selected.'
  MustSelectFirst: 'You must select the first block first.'
  NotEnoughBlocks: 'Not enough blocks in your inventory, You Need:'
  BlocksPlaced: 'Blocks placed successfully.'
  InvalidFirstBlock: '&cThe first selected block is AIR. Please select a valid block.'
  ConfigReloaded: 'Configuration has been reloaded.'
  InvalidSelection: 'You must select two blocks first.'